Repository hivemq/hivemq-edge, pull requests merged in 2023-08, with the labels that each got.

#30 feat(16109): Add PING event to usage data. Include session tracking.
  hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQEdgeHttpServiceImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQRemoteServiceImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/model/HiveMQEdgeEvent.java
  hivemq-edge/src/main/java/com/hivemq/edge/utils/HiveMQEdgeEnvironmentUtils.java
Labels: enhancement

#29 feat(16123): Ensure image URLs are served from API server
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/api/utils/ApiUtils.java
  hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java
Labels: enhancement

#32 feat (15617) - Ensure modules are loaded from workspace in development mode
  hivemq-edge/src/main/java/com/hivemq/edge/modules/ModuleLoader.java
  modules/hivemq-edge-module-modbus/build.gradle.kts
  modules/hivemq-edge-module-opcua/build.gradle.kts
Labels: enhancement

#36 fix (16220) - Backed off (terminal) error jobs are not removed from pool
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/ProtocolAdapterPollingServiceImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/params/ProtocolAdapterPollingInput.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/params/impl/ProtocolAdapterPollingInputImpl.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/impl/ModbusClient.java
Labels: bug

#37 fix (16221 - 16225) - Ensure the Protocol XML adapter created wrapper type correctly
  README.adoc
  hivemq-edge/src/main/java/com/hivemq/configuration/reader/ArbitraryValuesMapAdapter.java
  hivemq-edge/src/main/java/com/hivemq/configuration/reader/ConfigFileReaderWriter.java
  hivemq-edge/src/test/java/com/hivemq/configuration/writer/AbstractConfigWriterTest.java
  hivemq-edge/src/test/java/com/hivemq/configuration/writer/ConfigFileWriterTest.java
  hivemq-edge/src/test/java/com/hivemq/configuration/writer/ConfigurationServiceSyncTest.java
Labels: bug

#43 feat(16258): Show which protocol the user is creating/editing and adapter for
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.tsx
Labels: enhancement

#46 feat(16309): Add HiveMQ Edge Version number to the UI
  hivemq-edge/src/frontend/src/api/hooks/useGatewayPortal/__handlers__/index.ts
  hivemq-edge/src/frontend/src/modules/Dashboard/components/SidePanel.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/Dashboard/components/SidePanel.tsx
Labels: enhancement

#47 fix (16316) - Set and agent value in user properties
  hivemq-edge/src/main/java/com/hivemq/bridge/BridgeMqttClientFactory.java
  hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/BridgeMqttClient.java
  hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java
Labels: enhancement

#45 fix (16310) - Ensure OPC adapter does not block on initialisation thread
  hivemq-edge/src/main/java/com/hivemq/HiveMQEdgeGateway.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
Labels: bug, enhancement

#42 fix(16313) - Use coersive manipulation of empty strings for pojo types
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationConfigConverter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterFactory.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterFactory.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterUtils.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusConfigConverter.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterFactory.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterFactory.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaConfigConverter.java
Labels: enhancement

#54 feat (16351) - Generator updated with new abstracts and updates gradle env
  ext/polling-adapter-template.zip
  hivemq-edge/src/main/java/com/hivemq/tools/CreateAdapterBlueprint.java
Labels: enhancement

#52 feat(16385) - Export configuration exposed through API
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/FrontendResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/configuration/entity/gateway/ConfigurationExportEntity.java
  hivemq-edge/src/main/java/com/hivemq/configuration/entity/gateway/MutableConfigurationEntity.java
  hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java
Labels: enhancement
