Repository hivemq/hivemq-edge, pull requests merged in 2023-11, with the labels that each got.

#173 Fix (17366) - OPC - UA Background connection monitoring
  hivemq-edge/src/main/java/com/hivemq/api/model/core/Payload.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
Labels: bug, adapter

#189 Adds intro video of HiveMQ Edge as simple screencast
  README.adoc
  docs/.gitattributes
  docs/edge-intro.gif
Labels: cla-signed

#190 feat(17596) - PLC4X threading, S7 connection, ADS adapter, Http Untrusted SSL
  build.gradle.kts
  ext/release-process.txt
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/hooks/useGetUISchema.ts
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/ProtocolAdapterDataSample.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapter.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConfig.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/model/HttpData.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/model/ModBusData.java
  modules/hivemq-edge-module-plc4x/build.gradle.kts
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xConnection.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xDataUtils.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/model/Plc4xAdapterConfig.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/model/Plc4xDataType.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7AdapterConfig.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapter.java
  settings.gradle.kts
Labels: enhancement, adapter

#183 CI / fix cypress binaries
  .github/actions/setup_node/action.yml
  .github/workflows/frontend-cli.yml
Labels: cla-signed

#194 fix(16319): Fix the colour of the links' border in the navigation panel
  hivemq-edge/src/frontend/src/modules/Dashboard/components/NavLink.tsx
Labels: cla-signed

#193 fix(17493): Fix the alignment of the column's headers in the pafinated table
  hivemq-edge/src/frontend/src/components/PaginatedTable/PaginatedTable.tsx
Labels: cla-signed

#191 feat(17451): add date filtering on the Event Log
  hivemq-edge/src/frontend/src/components/DateTime/DateTimeRangeSelector.tsx
  hivemq-edge/src/frontend/src/components/DateTime/components/Option.spec.cy.tsx
  hivemq-edge/src/frontend/src/components/DateTime/components/Option.tsx
  hivemq-edge/src/frontend/src/components/DateTime/components/OptionBadge.spec.cy.tsx
  hivemq-edge/src/frontend/src/components/DateTime/components/OptionBadge.tsx
  hivemq-edge/src/frontend/src/components/DateTime/components/OptionCommand.spec.cy.tsx
  hivemq-edge/src/frontend/src/components/DateTime/components/OptionCommand.tsx
  hivemq-edge/src/frontend/src/components/DateTime/hooks/useRangeTranslation.spec.ts
  hivemq-edge/src/frontend/src/components/DateTime/hooks/useRangeTranslation.ts
  hivemq-edge/src/frontend/src/components/DateTime/types.ts
  hivemq-edge/src/frontend/src/components/DateTime/utils/range-option.mocks.ts
  hivemq-edge/src/frontend/src/components/DateTime/utils/range-option.utils.spec.ts
  hivemq-edge/src/frontend/src/components/DateTime/utils/range-option.utils.ts
  hivemq-edge/src/frontend/src/components/PaginatedTable/components/Filter.tsx
  hivemq-edge/src/frontend/src/locales/en/components.json
Labels: cla-signed

#196 fix license headers
  hivemq-edge/build.gradle.kts
  hivemq-edge/src/main/java/com/hivemq/api/model/adapters/AdapterStatusModelConversionUtils.java
  hivemq-edge/src/main/java/com/hivemq/api/model/adapters/ProtocolAdapterCategory.java
  hivemq-edge/src/main/java/com/hivemq/api/model/core/Payload.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/EventResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdapterApiUtils.java
  hivemq-edge/src/main/java/com/hivemq/edge/impl/events/EventServiceDelegateImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/impl/events/InMemoryEventImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/model/HiveMQEdgeRemoteEvent.java
  hivemq-edge/src/main/java/com/hivemq/edge/model/HiveMQEdgeRemoteServices.java
  hivemq-edge/src/main/java/com/hivemq/edge/model/Identifiable.java
  hivemq-edge/src/main/java/com/hivemq/edge/model/TypeIdentifier.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/AbstractProtocolAdapterJsonPayload.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/ProtocolAdapterDataSample.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/TagSample.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingPerSubscriptionAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapterInformation.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/metrics/ProtocolAdapterMetricsHelper.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterCapability.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterValidator.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/model/ProtocolAdapterValidationFailure.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/events/EventListener.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/events/EventService.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/events/EventStore.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/events/EventUtils.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/config/impl/AbstractPollingProtocolAdapterConfig.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/config/impl/AbstractProtocolAdapterConfig.java
  hivemq-edge/src/main/java/com/hivemq/edge/utils/HiveMQEdgeEnvironmentUtils.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterUtils.java
  hivemq-edge/src/main/java/com/hivemq/tools/CreateAdapterBlueprint.java
  hivemq-edge/src/main/java/com/hivemq/tools/PropertyReplacer.java
Labels: cla-signed

#197 bugfix > fix behavior change by making fields not mandatory
  hivemq-edge/src/main/java/com/hivemq/edge/modules/config/impl/AbstractProtocolAdapterConfig.java
Labels: cla-signed

#192 feat(17327): Create a consistent user-friendly rendering of Data/Time info
  hivemq-edge/src/frontend/src/api/hooks/useEvents/__handlers__/index.ts
  hivemq-edge/src/frontend/src/components/DateTime/DateTimeRenderer.spec.cy.tsx
  hivemq-edge/src/frontend/src/components/DateTime/DateTimeRenderer.tsx
  hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.spec.ts
  hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.ts
  hivemq-edge/src/frontend/src/modules/EventLog/components/panel/EventDrawer.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/EventLog/components/panel/EventDrawer.tsx
  hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.tsx
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/panels/ProtocolAdapters.tsx
Labels: cla-signed

#198 Bugfix/vogler update endpoint option
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaAdapterConfig.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaEndpointFilter.java
  modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/OpcUaEndpointFilterTest.java
Labels: cla-signed

#199 Bugfix/ads adapter service loading
  hivemq-edge/src/main/java/com/hivemq/api/auth/jwt/JwtAuthenticationProvider.java
  modules/hivemq-edge-module-plc4x/src/main/resources/META-INF/services/org.apache.plc4x.java.api.PlcDriver
Labels: cla-signed

#202 Bugfix/fix breaking changes in payload
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/ProtocolAdapterPublisherJsonPayload.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
  modules/hivemq-edge-module-http/build.gradle.kts
  modules/hivemq-edge-module-http/gradle.properties
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConfig.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
  modules/hivemq-edge-module-http/src/test/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterTest.java
  modules/hivemq-edge-module-modbus/build.gradle.kts
  modules/hivemq-edge-module-modbus/gradle.properties
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusAdapterConfig.java
  modules/hivemq-edge-module-modbus/src/test/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterTest.java
Labels: cla-signed

#200 Fix build.gradle.kts registering tasks multiple times
  build.gradle.kts
Labels: cla-signed

#195 feat(17448): Add a reduced version of the event log to the overview of entities in the workspace
  hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.spec.ts
  hivemq-edge/src/frontend/src/components/PaginatedTable/PaginatedTable.tsx
  hivemq-edge/src/frontend/src/locales/en/translation.json
  hivemq-edge/src/frontend/src/modules/App/routes.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/controls/NodePanelController.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.tsx
  hivemq-edge/src/frontend/src/modules/EventLog/components/table/EventLogTable.tsx
  hivemq-edge/src/frontend/src/modules/Welcome/components/Metrics.tsx
Labels: cla-signed

#201 fix(17476): Add support for Bridge nodes in the workspace
  hivemq-edge/src/frontend/src/locales/en/translation.json
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/controls/NodePanelController.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeAdapter.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeBridge.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeEdge.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeListener.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/parts/NodeNameCard.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/parts/NodeNameCard.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/parts/NodeWrapper.tsx
Labels: cla-signed

#204 fix(17700): Improve the UX of the metrics panel in the workspace
  hivemq-edge/src/frontend/src/api/hooks/useGetMetrics/__handlers__/index.ts
  hivemq-edge/src/frontend/src/locales/en/translation.json
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/NodePropertyDrawer.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/nodes-utils.ts
  hivemq-edge/src/frontend/src/modules/Metrics/Metrics.tsx
  hivemq-edge/src/frontend/src/modules/Metrics/components/MetricNameSelector.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/Metrics/components/MetricNameSelector.tsx
  hivemq-edge/src/frontend/src/modules/Metrics/components/Sample.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/Metrics/components/Sample.tsx
  hivemq-edge/src/frontend/src/modules/Metrics/components/SampleRenderer.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/Metrics/components/SampleRenderer.tsx
  hivemq-edge/src/frontend/src/modules/Metrics/utils/metrics-name.utils.spec.ts
  hivemq-edge/src/frontend/src/modules/Metrics/utils/metrics-name.utils.ts
  hivemq-edge/src/frontend/src/modules/Theme/styles/Stat.ts
  hivemq-edge/src/frontend/src/modules/Welcome/components/Metrics.tsx
  hivemq-edge/src/frontend/src/modules/Welcome/components/Sample.tsx
Labels: cla-signed

#206 feat(17787): refactor copy-to-clipboard component
  hivemq-edge/src/frontend/src/components/Chakra/ClipboardCopyIconButton.spec.cy.tsx
  hivemq-edge/src/frontend/src/components/Chakra/ClipboardCopyIconButton.tsx
  hivemq-edge/src/frontend/src/locales/en/components.json
  hivemq-edge/src/frontend/src/modules/Metrics/Metrics.tsx
  hivemq-edge/src/frontend/src/modules/Metrics/components/Sample.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/Metrics/components/Sample.tsx
Labels: cla-signed

#208 fix(17869): Improve date/time rendering for seconds
  hivemq-edge/src/frontend/src/components/DateTime/DateTimeRenderer.tsx
  hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.spec.ts
  hivemq-edge/src/frontend/src/components/DateTime/utils/duration.utils.ts
  hivemq-edge/src/frontend/src/locales/en/components.json
Labels: cla-signed

#207 fix(17782): Fix duplicated keys in onboarding tasks
  hivemq-edge/src/frontend/src/components/ConnectionController/ConnectionController.spec.tsx
  hivemq-edge/src/frontend/src/components/ConnectionController/ConnectionController.tsx
  hivemq-edge/src/frontend/src/locales/en/translation.json
  hivemq-edge/src/frontend/src/modules/Welcome/components/Onboarding.tsx
  hivemq-edge/src/frontend/src/modules/Welcome/hooks/useOnboarding.tsx
Labels: cla-signed

#209 Feature: Capability Service
  hivemq-edge/src/main/java/com/hivemq/api/ioc/ApiModule.java
  hivemq-edge/src/main/java/com/hivemq/api/model/ApiBodyExamples.java
  hivemq-edge/src/main/java/com/hivemq/api/model/capabilities/Capability.java
  hivemq-edge/src/main/java/com/hivemq/api/model/capabilities/CapabilityList.java
  hivemq-edge/src/main/java/com/hivemq/api/model/components/GatewayConfiguration.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/FrontendApi.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/FrontendResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/bootstrap/ioc/Injector.java
  hivemq-edge/src/main/java/com/hivemq/bootstrap/ioc/Services.java
  hivemq-edge/src/main/java/com/hivemq/edge/HiveMQCapabilityService.java
  hivemq-edge/src/main/java/com/hivemq/edge/impl/capability/CapabilityServiceImpl.java
Labels: cla-signed

#213 Bugfix: Fix missing buffering before first connect of bridge
  hivemq-edge/src/main/java/com/hivemq/bridge/BridgeService.java
  hivemq-edge/src/main/java/com/hivemq/bridge/MessageForwarderImpl.java
  hivemq-edge/src/main/java/com/hivemq/bridge/MqttForwarder.java
  hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/BridgeMqttClient.java
  hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/RemoteMqttForwarder.java
  hivemq-edge/src/main/java/com/hivemq/configuration/service/InternalConfigurations.java
  hivemq-edge/src/test/java/com/hivemq/bridge/mqtt/RemoteMqttForwarderTest.java
Labels: cla-signed

#216 Bugfix: Data loss on update of bridge
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/BridgeResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/bootstrap/ioc/Services.java
  hivemq-edge/src/main/java/com/hivemq/bridge/BridgeService.java
  hivemq-edge/src/main/java/com/hivemq/bridge/MessageForwarder.java
  hivemq-edge/src/main/java/com/hivemq/bridge/MessageForwarderImpl.java
  hivemq-edge/src/main/java/com/hivemq/bridge/config/LocalSubscription.java
  hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/BridgeMqttClient.java
  hivemq-edge/src/test/java/com/hivemq/bridge/config/LocalSubscriptionTest.java
Labels: cla-signed

#210 fix(): Adds OpenAPI Spec for 2023.8
  ext/hivemq-edge-openapi-2023.8.yaml
Labels: cla-signed
