Repository hivemq/hivemq-edge, pull requests merged in 2023-10, with the labels that each got.

#147 Feat (144) - Polling adapter instrumentation
  build.gradle.kts
  ext/module-templates/polling-adapter-template.zip
  hivemq-edge/src/main/java/com/hivemq/api/model/adapters/AdapterStatusModelConversionUtils.java
  hivemq-edge/src/main/java/com/hivemq/common/executors/ioc/ExecutorsModule.java
  hivemq-edge/src/main/java/com/hivemq/configuration/service/InternalConfigurations.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingPerSubscriptionAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/ProtocolAdapterPollingServiceImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/params/ProtocolAdapterPollingSampler.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/params/impl/ProtocolAdapterPollingSamplerImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
  hivemq-edge/src/main/java/com/hivemq/tools/CreateAdapterBlueprint.java
  hivemq-edge/src/main/resources/httpd/images/acme-icon.jpg
  hivemq-edge/src/main/resources/httpd/images/acme-icon.png
  hivemq-edge/src/test/java/com/hivemq/adapter/AdapterConfigFormatTest.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConfig.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xConnection.java
  settings.gradle.kts
Labels: enhancement, analysis

#153 Adapter validation framework changes
  hivemq-edge/src/main/java/com/hivemq/api/model/adapters/Adapter.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdapterApiUtils.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/ProtocolAdapterDiscoveryOutputImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/ProtocolAdapterPollingServiceImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/model/NodeTree.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/model/NodeType.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/model/ProtocolAdapterDiscoveryInput.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/model/ProtocolAdapterDiscoveryOutput.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/model/ProtocolAdapterInput.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/model/ProtocolAdapterPollingSampler.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/model/ProtocolAdapterStartInput.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/model/ProtocolAdapterStartOutput.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/model/impl/ProtocolAdapterPollingSamplerImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterFactory.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterInformation.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterFactory.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterInformation.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterPollingService.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterValidator.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/model/ProtocolAdapterValidationFailure.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterSchemaManager.java
  hivemq-edge/src/main/java/com/hivemq/protocols/params/NodeTreeImpl.java
  hivemq-edge/src/test/java/com/hivemq/adapter/TestAdapterInformation.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterFactory.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterInformation.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterFactory.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterInformation.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterFactory.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterInformation.java
  modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterAuthTest.java
  modules/hivemq-edge-module-opcua/src/test/java/com/hivemq/edge/adapters/opcua/payload/AbstractOpcUaPayloadConverterTest.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ab/ABProtocolAdapterFactory.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ab/ABProtocolAdapterInformation.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/bacnet/BacnetAdapterFactory.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/bacnet/BacnetAdapterInformation.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapterFactory.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapterInformation.java
Labels: enhancement

#146 feat(138): Custom editing field for topics in the adapter form
  hivemq-edge/src/frontend/package.json
  hivemq-edge/src/frontend/pnpm-lock.yaml
  hivemq-edge/src/frontend/src/__test-utils__/setup.ts
  hivemq-edge/src/frontend/src/api/hooks/useProtocolAdapters/__handlers__/index.ts
  hivemq-edge/src/frontend/src/components/Icons/TopicIcon.tsx
  hivemq-edge/src/frontend/src/components/MQTT/Topic.tsx
  hivemq-edge/src/frontend/src/components/MQTT/TopicCreatableSelect.spec.cy.tsx
  hivemq-edge/src/frontend/src/components/MQTT/TopicCreatableSelect.tsx
  hivemq-edge/src/frontend/src/config/index.ts
  hivemq-edge/src/frontend/src/hooks/useGetEdgeTopics/useGetEdgeTopics.spec.tsx
  hivemq-edge/src/frontend/src/hooks/useGetEdgeTopics/useGetEdgeTopics.tsx
  hivemq-edge/src/frontend/src/locales/en/components.json
  hivemq-edge/src/frontend/src/modules/Bridges/components/setup/TopicAutoComplete.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/drawers/WorkspaceOptionsDrawer.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/hooks/useGetFlowElements.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/hooks/useGetWorkspaceTopics.tsx
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/nodes-utils.spec.ts
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/nodes-utils.ts
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/topics-utils.spec.ts
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/utils/topics-utils.ts
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/drawers/AdapterInstanceDrawer.tsx
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/templates/BaseInputTemplate.tsx
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/templates/__internals/TopicInputTemplate.tsx
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/utils/validation-utils.ts
Labels: enhancement, accessibility

#172 PLC4X Version Increment
  hivemq-edge/src/frontend/src/locales/en/translation.json
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/hooks/useGetUISchema.ts
  modules/hivemq-edge-module-plc4x/build.gradle.kts
  modules/hivemq-edge-module-plc4x/gradle.properties
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xConnection.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xDataUtils.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/model/Plc4xAdapterConfig.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSAdapterConfig.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSConfigConverter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSProtocolAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSProtocolAdapterFactory.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSProtocolAdapterInformation.java
  modules/hivemq-edge-module-plc4x/src/main/resources/META-INF/services/com.hivemq.edge.modules.api.adapters.ProtocolAdapterFactory
  modules/hivemq-edge-module-plc4x/src/main/resources/httpd/images/beckhoff-icon.gif
Labels: adapter
