Repository hivemq/hivemq-edge, pull requests merged in 2023-09, with the labels that each got.

#70 fix(16511) - Ensure pings are NOT sent during a non-tracked runtime
  hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQEdgeHttpServiceImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQRemoteServiceImpl.java
Labels: bug

#69 feat(16497) - Strong typed categories through the API
  ext/hivemq-edge-openapi-2023.5.yaml
  hivemq-edge/src/main/java/com/hivemq/api/model/adapters/ProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/api/model/adapters/ProtocolAdapterCategory.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/ProtocolAdapterConstants.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterInformation.java
  hivemq-edge/src/test/java/com/hivemq/adapter/AdapterModelConverterTest.java
Labels: enhancement

#75 fix(16546) - Adapters create metrics in a consistent namespace
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/metrics/ProtocolAdapterMetricsHelper.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapter.java
  hivemq-edge/src/test/java/com/hivemq/adapter/ProtocolMetricsHelperTest.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaDataValueConsumer.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaSubscriptionConsumer.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaSubscriptionListener.java
Labels: bug, enhancement

#77 Fix (16580) - Fix modbus field ordering and allow API to control natural order
  hivemq-edge/src/test/java/com/hivemq/adapter/SchemaNodeGeneratorTest.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusAdapterConfig.java
Labels: bug, enhancement

#83 fix(16528): Allow remote adapters to be surfaced in the catalog
  hivemq-edge/src/frontend/src/api/hooks/useProtocolAdapters/__handlers__/index.ts
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/IntegrationStore/ProtocolsBrowser.spec.cy.tsx
  hivemq-edge/src/frontend/src/modules/ProtocolAdapters/components/IntegrationStore/ProtocolsBrowser.tsx
Labels: enhancement

#85 fix(2023.5): Fix double click on node
  hivemq-edge/src/frontend/src/modules/EdgeVisualisation/components/nodes/NodeAdapter.tsx
Labels: bug

#88 Fix(16649) - Edge started events being missed
  hivemq-edge/src/main/java/com/hivemq/edge/impl/HiveMQRemoteServiceImpl.java
Labels: bug

#91 Issue 86 - Modbus naming convention
  hivemq-edge/src/main/resources/hivemq-edge-configuration.json
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapterInformation.java
Labels: bug

#89 feat(16640) - Add gatekeeping to adapter discovery and allow adapters to determine if they wish to add support
  build.gradle.kts
  ext/hivemq-edge-openapi-2023.6.yaml
  hivemq-edge/src/main/java/com/hivemq/api/model/adapters/ProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/ProtocolAdaptersApi.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdapterApiUtils.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/api/utils/ApiErrorUtils.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/ProtocolAdapterInterceptorHandler.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapterInformation.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterCapability.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapterInformation.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
  hivemq-edge/src/test/java/com/hivemq/adapter/AdapterModelConverterTest.java
  hivemq-edge/src/test/java/com/hivemq/adapter/TestAdapterInformation.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapterInformation.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapterInformation.java
Labels: enhancement

#99 Fix(97) - Adapter Identifier needs start and end tokens
  hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java
  hivemq-edge/src/test/java/com/hivemq/adapter/AdapterConfigFormatTest.java
Labels: bug

#96 Feat(92) - Add default run configurations for developer runtime and adapter creation
  .gitignore
  .idea/runConfigurations/HiveMQ_Edge___Developer.xml
  .idea/runConfigurations/HiveMQ_Edge___New_Adapter.xml
  hivemq-edge/src/distribution/conf/developer-config.xml
  hivemq-edge/src/main/java/com/hivemq/configuration/ioc/ConfigurationFileProvider.java
  hivemq-edge/src/main/java/com/hivemq/edge/HiveMQEdgeConstants.java
Labels: enhancement, tracked

#102 fix(101) - UNS API validation is not aligned with UI and is flawed
  hivemq-edge/src/main/java/com/hivemq/api/model/uns/ISA95ApiBean.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/UnsResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/api/utils/ApiValidation.java
  hivemq-edge/src/test/java/com/hivemq/uns/UnsModelTest.java
Labels: bug

#114 fix(106) - Changed the URL of HTTP adapter to be URI format
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/configuration/reader/ConfigFileReaderWriter.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterUtils.java
  modules/hivemq-edge-module-http/build.gradle.kts
  modules/hivemq-edge-module-http/gradle.properties
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConfig.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConstants.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
  modules/hivemq-edge-module-http/src/test/java/com/hivemq/edge/adapters/http/TestHttpAdapterConfig.java
  modules/hivemq-edge-module-http/src/test/resources/http-config-empty-header.xml
  modules/hivemq-edge-module-http/src/test/resources/http-config-with-headers.xml
Labels: bug

#133 Polling adapter abstraction
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/DataType.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/data/ProtocolAdapterDataSample.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingPerSubscriptionAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractPollingProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationAdapterConfig.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationData.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/simulation/SimulationProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/config/impl/AbstractPollingProtocolAdapterConfig.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpAdapterConfig.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/HttpProtocolAdapter.java
  modules/hivemq-edge-module-http/src/main/java/com/hivemq/edge/adapters/http/model/HttpData.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusAdapterConfig.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/impl/ModbusClient.java
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/model/ModBusData.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/OpcUaProtocolAdapter.java
Labels: enhancement

#134 Transitions should return a response indicating status
  ext/hivemq-edge-openapi-2023.7.yaml
  hivemq-edge/src/main/java/com/hivemq/api/model/ApiBodyExamples.java
  hivemq-edge/src/main/java/com/hivemq/api/model/ApiConstants.java
  hivemq-edge/src/main/java/com/hivemq/api/model/status/Status.java
  hivemq-edge/src/main/java/com/hivemq/api/model/status/StatusTransitionResult.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/BridgeApi.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/ProtocolAdaptersApi.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/BridgeResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/bridge/BridgeService.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/ProtocolAdapterPollingServiceImpl.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterWrapper.java
Labels: enhancement

#136 fix(123): Change the text and colour of the stateless status badge
  hivemq-edge/src/frontend/src/locales/en/translation.json
  hivemq-edge/src/frontend/src/modules/Theme/themeHiveMQ.ts
Labels: enhancement
