Repository hivemq/hivemq-edge, pull requests merged in 2024-02, with the labels that each got.

#278 refactor(18991): Refactor "Transform" Operation to include serialisers
  hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/OperationData.json
  hivemq-edge/src/frontend/src/extensions/datahub/api/specs/OperationData.ts
  hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/FunctionNode.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/OperationNode.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/nodes/OperationNode.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/types.ts
  hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts
  hivemq-edge/src/frontend/tsconfig.json
  hivemq-edge/src/frontend/vite.config.ts
  hivemq-edge/src/frontend/vitest.config.ts
Labels: cla-signed

#277 fix intermittent warnings in adapter
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/eip/EIPProtocolAdapter.java
Labels: cla-signed

#282 feat(18960): Add connectivity and payload checks for behavior and transitions
  hivemq-edge/src/frontend/package.json
  hivemq-edge/src/frontend/pnpm-lock.yaml
  hivemq-edge/src/frontend/src/components/Mermaid.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/__test-utils__/react-flow.mocks.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/README.md
  hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/BehaviorPolicyData.json
  hivemq-edge/src/frontend/src/extensions/datahub/components/forms/TransitionSelect.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/forms/TransitionSelect.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/fsm/FiniteStateMachineFlow.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/fsm/MermaidRenderer.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/fsm/MermaidRenderer.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/fsm/ReactFlowRenderer.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/fsm/ReactFlowRenderer.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/fsm/StateNode.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/fsm/TransitionNode.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyEditor.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/flow/behavior_policy/BehaviorPolicyPanel.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/flow/behavior_policy/BehaviorPolicyPanel.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/flow/behavior_policy/BehaviorPolicySchema.ts
  hivemq-edge/src/frontend/src/extensions/datahub/flow/datahubRJSFWidgets.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/flow/transition/TransitionData.ts
  hivemq-edge/src/frontend/src/extensions/datahub/flow/transition/TransitionNode.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/flow/transition/TransitionPanel.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/flow/transition/TransitionPanel.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
  hivemq-edge/src/frontend/src/extensions/datahub/types.ts
Labels: cla-signed

#291 fix(19439) - CipherSuite placeholder text fix
  hivemq-edge/src/frontend/src/locales/en/translation.json
  hivemq-edge/src/frontend/src/modules/Bridges/components/panels/SecurityPanel.tsx
Labels: bug, cla-signed

#294 fix obfuscation > fix obfuscation
  hivemq-edge/src/main/java/com/hivemq/persistence/FilePersistence.java
Labels: cla-signed

#290 feat(17757) - Sanitized Logging
  hivemq-edge/src/main/java/com/hivemq/api/resources/impl/ProtocolAdaptersResourceImpl.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
  hivemq-edge/src/main/resources/logback.xml
  modules/hivemq-edge-module-modbus/src/main/java/com/hivemq/edge/adapters/modbus/ModbusProtocolAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/AbstractPlc4xAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/impl/Plc4xConnection.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ab/ABProtocolAdapter.java
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/siemens/S7ProtocolAdapter.java
Labels: bug, enhancement, adapter, cla-signed

#296 Bugfix: Fix keystore path being always empty
  hivemq-edge/src/main/java/com/hivemq/edge/modules/ModuleLoader.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaClientConfigurator.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/client/OpcUaEndpointFilter.java
  modules/hivemq-edge-module-opcua/src/main/java/com/hivemq/edge/adapters/opcua/util/KeystoreUtil.java
Labels: cla-signed

#260 fix(17211) - Cascase bridge and adapter metrics on delete / stop
  hivemq-edge/src/main/java/com/hivemq/bridge/metrics/PerBridgeMetrics.java
  hivemq-edge/src/main/java/com/hivemq/bridge/mqtt/BridgeMqttClient.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/impl/AbstractProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/adapters/metrics/ProtocolAdapterMetricsHelper.java
  hivemq-edge/src/main/java/com/hivemq/edge/modules/api/adapters/ProtocolAdapter.java
  hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterManager.java
  hivemq-edge/src/test/java/com/hivemq/adapter/ProtocolMetricsHelperTest.java
  hivemq-edge/src/test/java/com/hivemq/bridge/BridgeMetricsTest.java
Labels: bug, cla-signed

#297 feat(19709): Add tablular visualisation of policies, scripts and schemas
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubBehaviorPoliciesService/useCreateBehaviorPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubBehaviorPoliciesService/useDeleteBehaviorPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubBehaviorPoliciesService/useUpdateBehaviorPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubDataPoliciesService/useCreateDataPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubDataPoliciesService/useDeleteDataPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubDataPoliciesService/useUpdateDataPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubSchemasService/useCreateSchema.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubSchemasService/useDeleteSchema.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubScriptsService/useCreateScript.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubScriptsService/useDeleteScript.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/controls/PolicyToolbar.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxPublish.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DataHubListAction.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DataHubListAction.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/PolicyErrorReport.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/DataHubListings.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/DataHubListings.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/designer/behavior_policy/BehaviorPolicyNode.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/designer/data_policy/DataPolicyNode.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.spec.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.utils.spec.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.utils.ts
  hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
  hivemq-edge/src/frontend/src/extensions/datahub/routes.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/utils/toast.utils.ts
Labels: cla-signed

#293 feat(19497): Publish policy to the backend
  hivemq-edge/src/frontend/src/extensions/datahub/__test-utils__/react-flow.mocks.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/FunctionData.json
  hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/OperationData.json
  hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/SchemaData.json
  hivemq-edge/src/frontend/src/extensions/datahub/api/__generated__/schemas/_functions.json
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubBehaviorPoliciesService/useCreateBehaviorPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubBehaviorPoliciesService/useDeleteBehaviorPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubBehaviorPoliciesService/useUpdateBehaviorPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubDataPoliciesService/useCreateDataPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubDataPoliciesService/useDeleteDataPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubDataPoliciesService/useUpdateDataPolicy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubSchemasService/useCreateSchema.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubSchemasService/useDeleteSchema.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubScriptsService/useCreateScript.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/api/hooks/DataHubScriptsService/useDeleteScript.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/controls/ToolboxPublish.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/forms/VersionManagerSelect.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DataHubListAction.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/DataHubListAction.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/helpers/PolicyErrorReport.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/DataHubListings.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/DataHubListings.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/PolicyTable.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/SchemaTable.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/components/pages/ScriptTable.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.spec.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationNode.utils.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/operation/OperationPanel.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.spec.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/schema/SchemaNode.utils.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.spec.cy.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.utils.spec.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/script/FunctionNode.utils.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.spec.ts
  hivemq-edge/src/frontend/src/extensions/datahub/designer/validator/ValidatorNode.utils.ts
  hivemq-edge/src/frontend/src/extensions/datahub/hooks/usePolicyDryRun.spec.ts
  hivemq-edge/src/frontend/src/extensions/datahub/hooks/usePolicyDryRun.ts
  hivemq-edge/src/frontend/src/extensions/datahub/locales/en/datahub.json
  hivemq-edge/src/frontend/src/extensions/datahub/routes.tsx
  hivemq-edge/src/frontend/src/extensions/datahub/types.ts
  hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.spec.ts
  hivemq-edge/src/frontend/src/extensions/datahub/utils/node.utils.ts
  hivemq-edge/src/frontend/src/extensions/datahub/utils/store.utils.spec.ts
  hivemq-edge/src/frontend/src/extensions/datahub/utils/toast.utils.ts
Labels: cla-signed

#299 Fix: ads adapter port config not working
  modules/hivemq-edge-module-plc4x/src/main/java/com/hivemq/edge/adapters/plc4x/types/ads/ADSAdapterConfig.java
Labels: cla-signed
